### ISSUE TITLE
Fatal error on utilities class file inclusion

### ISSUE THREAD

**Issue by rony2k6** [eighty20results/e20r-single-use-trial#2]
Dear,

Hope you're doing well at your end.
I've got a fatal error from your plugin, regarding file inclusion below:

`PHP Fatal error:  require_once(): Failed opening required '../wp-content/plugins/e20r-single-use-trial/inc/utilities/class.utilties.php'. in /../wp-content/plugins/e20r-single-use-trial/e20r-single-use-trial.php on line 31`

This error causing wp sites show error screen.

**Comment by eighty20results** [comment]
Thanks for the report and the pull request! I've updated (and verified the update) how the plugin loads the Utilities module. 

Sorry about the trouble this caused!
